// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:721a1a5f-849f-471e-815b-e824278457f7",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_fg149TDp1",
  aws_user_pools_web_client_id: "79iv3oq426fkk703ovj0drno1c",
  oauth: {}
};

export default awsmobile;
